version: "3"
services:
  dev:
    image: docker-angular:dev
    container_name: docker-angular-dev
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
      - /app/node_modules
    stdin_open: true
    tty: true
  prod:
    image: docker-angular:prod
    container_name: docker-angular-prod
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
